### ISSUE TITLE
[FR] add monero donation address

### ISSUE THREAD

**Issue by ITwrx** [GrapheneOS/grapheneos.org#10]
It would be nice for privacy focused donors if there were a Monero/XMR address in addition to the BTC address.
thanks

**Comment by thestinger** [comment]
I'd likely want to wait until it's supported by the official Trezor wallet.

**Comment by ITwrx** [comment]
ok, monero devs/contributors also have an open source hardware wallet in the works, but idk how long that is going to take. also, i forgot about https://xmr.to/

**Comment by thestinger** [comment]
You can still leave this issue for now, I'm just unlikely to actually add it until I can do it with my existing Trezor hardware wallet that I use for Bitcoin. I wouldn't want to use a software wallet.

**Comment by ITwrx** [comment]
ok, cool. trezor T support supposed to be coming soon. https://www.reddit.com/r/Monero/comments/bk2i0z/trezor/

**Comment by plasmacorral** [comment]
8 months later and few hardware wallets are now supported:
https://www.getmonero.org/downloads/#hardware

Actual privacy with Monero may devolve over time, but the more people are exposed to chain analysis and forensics the more likely this crowd might be to adopt XMR.  What obstructions need to be addressed to help move this forward?

**Comment by thestinger** [comment]
This is implemented. Would appreciate if you could send a small test donation to confirm that it works properly.

**Comment by ITwrx** [comment]
@thestinger i just sent you 25 cents worth of monero. :) let me know if it works, pls.

**Comment by thestinger** [comment]
@ITwrx Yes, that worked. Thanks for helping to test it.

**Comment by ITwrx** [comment]
@thestinger sure. keep up the good work, and happy Festivas. May the Airing of Grievances be productive, and the Feats of Strength, inspiring!
