### ISSUE TITLE
Update to the CLI installation guide

### ISSUE THREAD

**Issue by actuallyamoose** [GrapheneOS/grapheneos.org#1003]
There is an oversight in the CLI installation guide located here : [https://grapheneos.org/install/cli#flashing-factory-images](url)

On some supported Linux distributions, in my case Debian 12, the default shell for scripts is dash rather than the standard bash. flash-all.sh cannot run properly under dash, but it does work under bash. The step should be updated to specify the following command when running on Linux for full compatibility:

`bash flash-all.sh`

rather than the current:
`sh flash-all.sh`

**Comment by thestinger** [comment]
Fixed, although we could change it to avoid this dependency again.
