### ISSUE TITLE
Edit F.A.Q. answer for clarity (Typo)

### ISSUE THREAD

**Issue by ibradley02** [GrapheneOS/grapheneos.org#103]
Under the section "Does GrapheneOS provide a firewall?"

The second sentence reads:
"The GrapheneOS project historically made various improvements to the firewall but over time most of these changes were been integrated upstream or became irrelevant."

I believe it should be changed to either:
 "...most of these changes were integrated upstream" or, 
"...most of these changes have been integrated upstream"

**Comment by thestinger** [comment]
Thanks, fixed this.
