### ISSUE TITLE
Add Trusted Types polyfill?

### ISSUE THREAD

**Issue by orazioedoardo** [GrapheneOS/grapheneos.org#1035]
A polyfill for Trusted Types is available to make the feature work on Safari and Firefox. Interested in pull request (or do it yourself)?

https://github.com/w3c/trusted-types?tab=readme-ov-file#browsers

**Comment by thestinger** [comment]
Don't really want to do this. We don't have significant JavaScript for the site other than the web installer which isn't yet compatible with it due to the zip library anyway.
