### ISSUE TITLE
Add Zcash shielded address option for donations

### ISSUE THREAD

**Issue by iAnonymous3000** [GrapheneOS/grapheneos.org#1046]
Currently only a transparent Zcash address is listed for donations. Consider adding a shielded address option for enhanced privacy.

Shielded addresses would:
- Hide transaction amounts and metadata
- Provide stronger privacy than transparent addresses
- Align with the project's privacy focus

The existing transparent address could remain as a fallback option.

![image](https://github.com/user-attachments/assets/bc38f6c6-973c-4610-801d-2112156836c5)

**Comment by thestinger** [comment]
It doesn't have hardware wallet support and we don't want to add more non-hardware-wallet options. Monero has hardware wallet support and we support that already.
