### ISSUE TITLE
Potentially outdated information?

### ISSUE THREAD

**Issue by boredsquirrel** [GrapheneOS/grapheneos.org#1056]
https://grapheneos.org/faq#file-transfer

> To use an external drive, plug it into the phone and use the system file manager to copy files to and from it. The only difference on GrapheneOS is USB peripherals such as USB flash drives will be ignored **unless they're plugged in at boot** or when the device is unlocked. You can configure this in Settings > Security > USB peripherals.

I hope this is not true. Simply rebooting a phone and plugging in a peripheral would bypass the USB block?

**Comment by thestinger** [comment]
It was out-of-date information from before the USB-C port control feature existed.

**Comment by boredsquirrel** [comment]
solved with https://github.com/GrapheneOS/grapheneos.org/commit/ae44e2374e6972cd60b413c3620286a8aa38fbe9
