### ISSUE TITLE
Enabling OEM unlocking: "For the Pixel 6a, OEM unlocking won't work with the version of the stock OS from the factory." How do I know if I have the Pixel 6a?

### ISSUE THREAD

**Issue by el-gallo-azul** [GrapheneOS/grapheneos.org#1058]
Or how do I confirm that I DON'T have the Pixel 6a? I just received this Google Pixel Tablet yesterday, and am installing GrapheneOS immediately.

**Comment by thestinger** [comment]
Pixel Tablet is not a Pixel 6a. Pixel 6a is a specific phone.

**Comment by thestinger** [comment]
All Pixel Tablets can be unlocked.

**Comment by el-gallo-azul** [comment]
In that case, it would be better if it saId, ""For the Pixel 6a telephone, OEM unlocking won't work with the version of the stock OS from the factory."
