### ISSUE TITLE
WebUSB installer: Missing instructions for Debian 12 (Bookworm)

### ISSUE THREAD

**Issue by hweimer** [GrapheneOS/grapheneos.org#1065]
When trying to use the WebUSB installer under Debian 12, I had to install adb and fastboot as well for it to work. Merely installing android-sdk-platform-tools-common was not sufficient and still gave me the error "failed to execute 'open' on 'USBDevice': Access denied."

**Comment by thestinger** [comment]
That doesn't sound right. Are you sure you didn't just not plug it in again after adding it? The rules don't apply immediately, it's bad UX.
