### ISSUE TITLE
Web Installer guide has sightly outdated information regarding fwupd on Debian/Ubuntu

### ISSUE THREAD

**Issue by rslurry** [GrapheneOS/grapheneos.org#1088]
Currently the Web Installer guide says that Debian and Ubuntu have an outdated fwupd package that causes issues with the install, and that problem is solved by fwupd versions >=1.9.10.  I just checked Ubuntu 24.04.1 and it has fwupd version 1.9.24 by default.  I can't confirm if this is also the case for the latest Debian release, but I suspect it might not be given it lags 1-2 years behind.

I recommend updating the language of the guide accordingly (e.g., "Debian stable and Ubuntu **may** have an outdated fwupd package ...").

I think it would also be good to include a command to check the installed version, e.g., `apt-cache policy fwupd`, to make it easier for less technical users to check and know whether or not they need to worry about this.

**Comment by thestinger** [comment]
It's going to remain as it is because it appears the newer versions of fwupd may still cause problems.

**Comment by rslurry** [comment]
I used a totally fresh install of Ubuntu 24.04.1 and had zero problems installing GOS.  If fwupd 1.9.24 caused problems, wouldn't that have prevented me from completing the install without stopping the service as instructed in the current Web Installer guide?  The absolute language in the current guide is clearly not 100% correct and should be corrected, perhaps not exactly as I suggested, but at a minimum using more reasonable language, e.g., "may need to stop the service".

**Comment by thestinger** [comment]
https://packages.debian.org/search?keywords=fwupd
https://launchpad.net/ubuntu/+source/fwupd

Ubuntu 24.10 and 24.04 have a new enough version, but the other still supported stable releases don't have it. We could change the wording to be specific about which versions require it but that will continue making the guide more complex. Another option is dropping support for Debian and Ubuntu versions older than 24.04.

**Comment by rslurry** [comment]
The guide mentions that fwupd 1.9.10 and later do not have this issue, is that confirmed?  Taking a step back, I think the guide could be made more general and therefore easier to maintain while addressing this difference between Ubuntu 24.04+ vs. older versions without having to specifically identify them, as there are other Debian- and Ubuntu-based distributions (e.g., Kali, PopOS, SteamOS) that are not mentioned as supported in the current guide but would likely work for the install given their origins.  The section could instead say something like,

"Some Debian, Ubuntu, and derivative distributions have an outdated fwupd package with a bug breaking connecting to Android's bootloader interface (fastboot) while fwupd is running since it tries to connect to arbitrary devices. This section can be skipped on Arch Linux and other distributions with fwupd 1.9.10 or later since we reported the bug and it was fixed. This never impacted Android or ChromeOS.

Check your fwupd version with the following command:
```apt-cache policy fwupd```

If the installed version is less than 1.9.10, you can stop fwupd with the following command:

```sudo systemctl stop fwupd.service```

This doesn't disable the service and it will start again on reboot."

In this way, you don't need to revisit this until years from now when Debian and Ubuntu drop support for the current LTS versions that have the outdated package.

If you are open to the suggested change, I have submitted a pull request with it.

**Comment by thestinger** [comment]
> The guide mentions that fwupd 1.9.10 and later do not have this issue, is that confirmed?

It's confirmed that their attempted fix shipped in 1.9.10. It's not confirmed that their fix fully works or that new issues haven't been introduced since then.

**Comment by rslurry** [comment]
I see.  Well, we know that 1.9.24 works, given my test.  It doesn't look like they have changed much related to this since 1.9.10, so I'd be included to assume it works for 1.9.10 - 1.9.23 and >1.9.24 as well.

**Comment by jermanuts** [comment]
Can confirm that fwupd doesn't need to be disabled on Fedora atomic
