### ISSUE TITLE
Give full commands for "Flashing as non-root" on web installer

### ISSUE THREAD

**Issue by jermanuts** [GrapheneOS/grapheneos.org#1089]
Give full commands for "[Flashing as non-root](https://grapheneos.org/install/web#flashing-as-non-root)" on web installer just like it is on [CLI page](https://grapheneos.org/install/cli#flashing-as-non-root)
 
On Arch Linux:

`sudo pacman -S android-udev`

On Debian and Ubuntu:

`sudo apt install android-sdk-platform-tools-common`

The web installer is targeted for normal users, so giving them the commands straight up to copy+paste, is much more convenient.

**Comment by thestinger** [comment]
We avoided that with the assumption people would use a GUI to install it on Ubuntu.

**Comment by jermanuts** [comment]
Well.. you can mention that you can use GUI, and also provide the commands for terminal usage, because I think most people will just want such commands ready for instant copy+paste.

**Comment by thestinger** [comment]
These distributions should really just fix their USB support to avoid needing custom udev rules to access USB devices as a local user. It's not a reasonable way of controlling USB access. What people actually need is having apps sandboxed with the ability to choose one or more USB devices for them to access via a permission dialog. They don't implement anything like that but that's how it works on Android or in a browser with WebUSB. We don't really want to have CLI commands in the web install guide.

**Comment by jermanuts** [comment]
>We don't really want to have CLI commands in the web install guide.

I have seen people new to Linux getting confused on how to install these packages, you may have also seen the same issue on your support channel. So, for the time being, you may re-consider it incase the number of people getting confused increases.

**Comment by thestinger** [comment]
Having CLI commands in the web installer guide goes against how it's meant to work and would draw into question why those operating systems are marked officially supported. We don't want to tell people to use the CLI for something they can use the GUI in the non-CLI installation guide.
