### ISSUE TITLE
Ukrainian SIM card not showing Signal on Graphene

### ISSUE THREAD

**Issue by aceonlinebs** [GrapheneOS/grapheneos.org#118]
Hi,
I have GrapehenOS installed on a Pixel 3a XL and works good without a SIM.

- I have 3 new Ukranian SIM cards, all of them work on iPhones with latest iOS and Huwawi Android phone.
- I have 2 other countries SIM cards that work with Graphene on the  Pixel 3a XL.

When inserting the Ukranian SIM cards to the Pixel, the Graphene recognizes the carrier, but there is no network Signal. I tried to choose Network manually and i shows all Ukranian Carriers as option, but even if I choose the relevant network, it does not get network signal for calls.

Is there anything I can do resolve it, or somehow provide you information to help resolve it? I would like to use the phone in ANY country that I am in.

Thanks

**Comment by thestinger** [comment]
How long are you waiting for it?

**Comment by aceonlinebs** [comment]
at some point i thought its really time related, so i just kept sim in all day. its there even now as we speak

**Comment by thestinger** [comment]
Did you figure it out?
