### ISSUE TITLE
Possible typo in /faq#legacy-devices

### ISSUE THREAD

**Issue by gosh-darn** [GrapheneOS/grapheneos.org#133]
Is it suppose to say _Even if the community was prepared to take over maintenance of the open source code and to replace the rest, firmware would present a major issue, and the community has never been active or interested enough **in in** device support to consider attempting this_?
Specifically the two consecutive **in**s. It is at the very least not syntax I'm familiar with.

**Comment by thestinger** [comment]
Pushed a fix for this.

**Comment by gosh-darn** [comment]
Thanks!
