### ISSUE TITLE
Clarify carrier support

### ISSUE THREAD

**Issue by tomkel** [GrapheneOS/grapheneos.org#136]
https://freenode.logbot.info/grapheneos/20200730#c4574572
> Sprint is not supported by GrapheneOS as they require crap installed

https://freenode.logbot.info/grapheneos/20200726#c4521223

> Sprint requires some pretty invasive stuff on the phone in order for it to work en.m.wikipedia.org/wiki/OMA_Device_Management

> T-Mobile and MVNOs on their network just seem to be the best value all around and they have great coverage for the most part

**Comment by thestinger** [comment]
I'm not sure what there is to clarify. GrapheneOS IRC / Matrix channel is not documentation.

**Comment by thestinger** [comment]
If you have questions about whether a carrier supports non-carrier devices without their proprietary carrier apps, you should contact the carrier. There are a huge number of carriers in the world. It's not something that we'll document. It's up to them to document it.

**Comment by tomkel** [comment]
> If you have questions about whether a carrier supports non-carrier devices without their proprietary carrier apps, you should contact the carrier. There are a huge number of carriers in the world. It's not something that we'll document. It's up to them to document it.

Well, then this sentence you typed could be included on the site, could it not? "We know there may be compatibility issues with some carriers, such as Sprint" ? I think it would be a friendly thing to your users to include it, to give them a heads up. Rather than them trying to install, it not working right, getting support from other users in the channel, and then switching carriers after the fact.

**Comment by tomkel** [comment]
What is the downside of including a sentence on the website?

**Comment by theaeonsolution** [comment]
@tomkel you need to go to the Sprint store and make sure the sim card you are using is supported for the Pixels on Sprint's network. A representative can check for you if your sim card is supported or if you need a new sim card. Do not use an eSIM for setting up the phone. Then confirm in the store or through Sprint support if your phone's IMEI is registered with them. After that, set the Preferred network type to "3G".

**Comment by theaeonsolution** [comment]
> > If you have questions about whether a carrier supports non-carrier devices without their proprietary carrier apps, you should contact the carrier. There are a huge number of carriers in the world. It's not something that we'll document. It's up to them to document it.
> 
> Well, then this sentence you typed could be included on the site, could it not? "We know there may be compatibility issues with some carriers, such as Sprint" ? I think it would be a friendly thing to your users to include it, to give them a heads up. Rather than them trying to install, it not working right, getting support from other users in the channel, and then switching carriers after the fact.

You are welcome to create a pull request that concisely documents this issue with carriers. The user is ultimately responsible for finding carriers that support GrapheneOS and contacting them for Mobile network support.

**Comment by tomkel** [comment]
great, thanks!
