### ISSUE TITLE
Add a .onion mirror for the site

### ISSUE THREAD

**Issue by Bosch-0** [GrapheneOS/grapheneos.org#150]
As GrapheneOS users are generally privacy / security focused it would make sense to have a .onion mirror of the site that can be accessed via Tor.

**Comment by equwal** [comment]
Anyone can host this if interested. I might do it later.

**Comment by Zanthed** [comment]
GrapheneOS doesn't really want unofficial websites and would rather want an official link that can be verified is ours.

**Comment by equwal** [comment]
On 21/12/02 04:32AM, June wrote:
> GrapheneOS doesn't really want unofficial websites and would rather want an official link that can be verified is ours.

Cool than make one yourself and I'll not do one, unless you don't, in
which case I will.

--
CAEE B377 FC82 BAF9 102C  D22F C5CE D003 1AA8 E281
Spenser Truex        https://equwal.com

**Comment by thestinger** [comment]
It's not safe for people to be getting information from an unofficial site or especially downloading anything from it.

**Comment by equwal** [comment]
On 21/12/07 11:22PM, Daniel Micay wrote:
> It's not safe for people to be getting information from an unofficial site or especially downloading anything from it.

Just sign the downloads. Any serious open source project website has a
million unofficial mirrors.

Besides, this site has MIT license :P

Or just make your own onion and i2p so I won't bother
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/GrapheneOS/grapheneos.org/issues/150#issuecomment-988562235

--
CAEE B377 FC82 BAF9 102C  D22F C5CE D003 1AA8 E281
Spenser Truex        https://equwal.com

**Comment by thestinger** [comment]
The site's code has an MIT license. The rules for using the trademark are different.

**Comment by equwal** [comment]
On 21/12/08 11:37AM, Daniel Micay wrote:
> The site's code has an MIT license. The rules for using the trademark are different.

Good point, I'll make a fantastic parody.

--
CAEE B377 FC82 BAF9 102C  D22F C5CE D003 1AA8 E281
Spenser Truex        https://equwal.com

**Comment by r3g-5z** [comment]
Based on a conversation in #infrastructure:grapheneos.org, we're not interested in anything Tor.
