### ISSUE TITLE
Potentially replace bsdtar with libarchive-tools

### ISSUE THREAD

**Issue by kornpow** [GrapheneOS/grapheneos.org#157]
On Ubuntu 20.04 I cannot find bsdtar in the apt sources:
```
Package bsdtar is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libarchive-tools:i386 libarchive-tools

E: Package 'bsdtar' has no installation candidate
```
I installed libarchive-tools which included bsdtar, and everything else worked!

**Comment by thestinger** [comment]
I've updated this now. It seems `bsdtar` was the old package name and it was renamed. Ubuntu doesn't have the transitional package. I hadn't tested it on Ubuntu.
