### ISSUE TITLE
Pixel 4a driver needed for Win10 during install.

### ISSUE THREAD

**Issue by 00Roc** [GrapheneOS/grapheneos.org#165]
The GrapheneOS instructions do not indicate this for win10.  This is something that should be listed in the installation instructions.

The link to access to the most current Google USB driver can be found here:
https://developer.android.com/studio/run/win-usb

(The current linked install version is directly accessed here, but this will change over time)
https://dl.google.com/android/repository/usb_driver_r13-windows.zip

**Comment by thestinger** [comment]
You don't need to install the driver from Google. You can get it from Windows Update or Device Manager.

**Comment by 00Roc** [comment]
Tried Device Manager - didn't work.  Installed a pack from MSFT that was
supposed to work as well, but didn't.  Didn't try windows update after the
device was connected though.

**Comment by thestinger** [comment]
It doesn't show up before the device is connected in fastboot mode.

**Comment by thestinger** [comment]
For many users, it appears to get installed automatically. Not clear why that isn't the case for everyone.

**Comment by thestinger** [comment]
This is documented now.
