### ISSUE TITLE
WebUSB Installer is broken when clicking Download Release button

### ISSUE THREAD

**Issue by swdee** [GrapheneOS/grapheneos.org#249]
We are using the WebUSB based installer here https://grapheneos.org/install/web to install GrapheneOS on a Pixel 5.  This is being installed from Ubuntu 20.04.3 using Chrome v93.0.4577.63.

Following the instructions on that page work up until the point when we click on the "Download Release" button.  Upon clicking the download button an error message appears below it saying "Error: undefined".

Opening up the browser console reveals a javascript error as per the screen shot when attempting to download the release file.

![gos-install-err](https://user-images.githubusercontent.com/8000937/131631013-baf19036-47f7-4fbe-ad7a-b584dc9caa0a.png)

The key error line is;

```
GET http://releases.grapheneos.org/redfin-factory-2021082501.zip net::ERR_FAILED 200
```

By beautifying the packed javascript file `web-install.js` it shows the execution point where error occurs.

![gos-pretty-code](https://user-images.githubusercontent.com/8000937/131631261-eca74461-7dd3-4852-afb7-efb0c1e97d67.png)

**Comment by thestinger** [comment]
Are you using Incognito mode? It doesn't provide enough storage space. It's also possible that you have too low storage space overall and the browser is restricting the page from having enough.

**Comment by swdee** [comment]
Incognito mode was not being used, however I was using a Live USB for Ubuntu which only had 7GB free on `/` and assigns the rest of the USB capacity (100+GB) to `/var/log`.

Due to your concerns on too low storage space, I dropped in a new hard drive and did a full install of Ubuntu.  Started the WebUSB install again and this time it worked without issue.  

Thanks for your quick reply!
