### ISSUE TITLE
Request documentation guidance for apps to properly handle Network Permission

### ISSUE THREAD

**Issue by realbiz21** [GrapheneOS/grapheneos.org#258]
There are some applications that do not respond well to Network Permission being denied.

GrapheneOS throws a SecurityException and apps are not catching it and ultimately crash. I've logged issues in two apps I use so far:

- https://github.com/standardnotes/mobile/issues/491
- https://github.com/osmandapp/OsmAnd/issues/12841

I can potentially see this being bounced around as "not our problem" from both the app and GrapheneOS side. The only guidance I see on the grapheneos.org site is https://grapheneos.org/faq#firewall:

> GrapheneOS adds a user-facing Network permission toggle providing a robust way to deny both direct and indirect network access to applications. It builds upon the standard non-user-facing INTERNET permission, so it's already fully adopted by the app ecosystem. Revoking the permission denies indirect access via OS components and apps enforcing the INTERNET permission, such as DownloadManager. Direct access is denied by blocking low-level network socket access.

Can the GrapheneOS team supplement this text with some minimal guidance for app developers to give those of us logging issues against them direction in how to resolve?

**Comment by thestinger** [comment]
You're working to work on https://github.com/GrapheneOS/os-issue-tracker/issues/560.

**Comment by thestinger** [comment]
We already have https://github.com/GrapheneOS/os-issue-tracker/issues/560 filed and you're welcome to work on it. It's a relatively small amount of work but we're very busy with other things. We won't be documenting anything about this for app developers. It doesn't make sense.

**Comment by realbiz21** [comment]
Thanks for pointing to GrapheneOS/os-issue-tracker#560 though it doesn't explain how it intends to resolve the issue from an implementation perspective. If GrapheneOS already has a goal to increase app compatibility then the issue is covered. Thanks.
