### ISSUE TITLE
Is there any plan to support other phones?

### ISSUE THREAD

**Issue by dehghani-mehdi** [GrapheneOS/grapheneos.org#262]
I like to use GrapheneOS on my Samsung J710F

**Comment by akc3n** [comment]
> I like to use GrapheneOS on my Samsung J710F

Hi, 
That is not [supported](https://grapheneos.org/faq#supported-devices).
Please take a look at https://grapheneos.org/faq#future-devices

**Comment by dehghani-mehdi** [comment]
I know that is not supported, that's why I asked about their plan to support more devices, like mine.

**Comment by ghost** [comment]
@dehghani-mehdi If you read the FAQ, it tells you a non-exhaustive detailed description of what Pixels implement/Google does that other OEMs and other devices fail to implement or implement properly. There is a lot of reasoning behind the choice for Pixels which is all clearly documented in the FAQ regarding device support.
