### ISSUE TITLE
have official list on website of project-friendly vendors that sell GrapheneOS devices

### ISSUE THREAD

**Issue by mfc** [GrapheneOS/grapheneos.org#263]
would be great to have an official list on the GrapheneOS website that lists GrapheneOS vendors who support the project. this would help current or prospective GrapheneOS users navigate the market, given the [assumption that users will buy a device to run GrapheneOS](https://grapheneos.org/faq#when-devices) and some folks (especially companies) will want to purchase devices with GrapheneOS pre-installed.

i could imagine/guess this might include:
* [Nitrophone](https://shop.nitrokey.com/shop/product/nitrophone-1-199)
* [Ncryptcellular](https://shop.ncryptcellular.com.au/products/graphene-os-smartphone?variant=132)
* ?

could be used to highlight what vendors financially support the project (so if you purchase from them, that is also financially supporting the project). doesn't need to be structured similarly but here is [example from Qubes OS](https://www.qubes-os.org/doc/certified-hardware/) for potential inspiration.

this would also help such users avoid vendors that doesn't support the project or are malicious in some way.

**Comment by thestinger** [comment]
Not currently planned.
