### ISSUE TITLE
add bullet points with overview to main page

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/grapheneos.org#27]

**Comment by warren-fisher** [comment]
Working on this now. Will have a initial version shortly. I am thinking of adding a new heading above "Early stage of development"  titled "overview", with bullet points on some of the features, compatibility (currently no non-pixel devices, no google play services, etc... ) that will be of interest to anyone. I will look through some of the postings on the reddit and highlight common questions asked by newcomers and address some of them here. Thoughts?

**Comment by Peter-Easton** [comment]
https://github.com/Peter-Easton/grapheneos.org/blob/e85398ed38fd8a8d5ebbe481a937fce868586d69/static/index.html#L79

I tried to crib as much information from the sponsorship page and some of the overviews as I could and distill them down to around two paragraphs. Let me know if this works.

**Comment by thestinger** [comment]
It's a lot less bad now.
