### ISSUE TITLE
self-hosted report-uri / report-to server

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/grapheneos.org#28]
I want more access to these reports than https://report-uri.com provides.

**Comment by emanuelb** [comment]
Sentry is widely used open-source product (can be self-hosted) for tracking errors which also support receiving CSP violations:
https://docs.sentry.io/error-reporting/security-policy-reporting/
https://blog.sentry.io/2018/09/04/how-sentry-captures-csp-violations
in the future it will probably support both `Report-To` & `Feature-Policy-Report-Only` headers to receive more information.

**Comment by thestinger** [comment]
Not planned anymore. Haven't found these features useful and they've been removed.
