### ISSUE TITLE
update fastboot.js to v1.1.1 in prep for Pixel 6/6 Pro web installer

### ISSUE THREAD

**Issue by ghost** [GrapheneOS/grapheneos.org#302]
v1.1.1 release tree: https://github.com/kdrag0n/fastboot.js/tree/457f4564c30d8f251c92abd78371d2004c62fb8e

v1.1.0 added Pixel 6 and 6 Pro partitions and code changes/refactors
v1.1.1 updates dependencies

zip.js 2.3.19 has a bug causing OOM issues and has had its version pinned to 2.2.27: https://github.com/kdrag0n/fastboot.js/commit/a0cef2a0a8d60998f7c51a4c638635b819c4458a

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/grapheneos.org/commit/a1a56d1ad244a53beed35788155b5fef68af5ceb
