### ISSUE TITLE
Add documentation on the current status of using an eSIM with GrapheneOS

### ISSUE THREAD

**Issue by jorgeluiscarrillo** [GrapheneOS/grapheneos.org#327]
If feels like every day we get multiple people asking if eSIM is supported on GrapheneOS. Currently, we have been redirecting users to this [issue](https://github.com/GrapheneOS/os-issue-tracker/issues/159) on our tracker. I think it would be helpful if we documented that eSIMs are partially supported (including deleting) on GrapheneOS with the workaround mentioned in that issue. We should document the steps to get an eSIM working, explain why the workaround is required, and the plans for including an eSIM activation app in the future. This will hopefully reduce the amount of times we get asked this question and we won't need to redirect users to that issue anymore (and avoid more "I would like this feature!" comments).

**Comment by 1ILV1** [comment]
No. Not all devices are supported. Google pixel 3 has no any workaraunds mentioned on this issue. D2DS mode from INFO menu is missing. So no, esim supported BUT not for all devices.

**Comment by jorgeluiscarrillo** [comment]
As far as I'm aware, all currently supported GrapheneOS devices have the capability for eSIM, including the now legacy Pixel 3 devices. Should note that there is a typo, it's not `D2DS` but `DSDS`.

**Comment by 0xspade** [comment]
Hi guys,

Is the esim already working without reflashing it back to stock ROM? or do I still need to reflash it back?

**Comment by ghost** [comment]
@0xspade This is the issue tracker for the website itself.

Please ask support questions in our Matrix community. https://grapheneos.org/contact#community

**Comment by thestinger** [comment]
Not planned. Please work on proper support for it if you want it.

**Comment by thestinger** [comment]
This should just be properly implemented. It's one of the priorities after the app repository. The workaround is not officially supported and people should stick to physical SIMs until there's proper eSIM support unless they want to be using something not officially supported or tested. The documentation will not cover that.
