### ISSUE TITLE
Would absolutly LOVE the ability to create folders in the app drawer to make it less cluttered while not downloading a 3rd party launcher.

### ISSUE THREAD

**Issue by MoldyTaint** [GrapheneOS/grapheneos.org#367]
Would absolutly LOVE the ability to create folders in the app drawer tomake it less cluttered while not downloading a 3rd party launcher.

**Comment by Zanthed** [comment]
This is the issue tracker for the website.

Please use the os-issue-tracker for GrapheneOS-specific stuff: https://github.com/GrapheneOS/os-issue-tracker/issues
