### ISSUE TITLE
white on transparent background version of the logo in the navigation bar for the GrapheneOS item

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/grapheneos.org#4]

**Comment by warren-fisher** [comment]
Looking into this now. Although it is a bit unclear, I believe you mean replacing the blue GrapheneOS link in the navigation menu with a white on transparent background version of the GrapheneOS logo featured in the footer of the page. Let me know if this is correct, I will look into completing it if so (and if this enhancement is still something that is desired).

**Comment by thestinger** [comment]
Someone submitted https://github.com/GrapheneOS/grapheneos.org/pull/35 but I haven't had time to look at it yet.

**Comment by wxlfe** [comment]
Since #35 was closed, is this issue still open?

**Comment by thestinger** [comment]
This is still wanted by that implementation didn't meet the requirements. The account used to submit it ended up being deleted anyway.
