### ISSUE TITLE
Minor SMS Issue & Feature requests

### ISSUE THREAD

**Issue by ToddCrimson** [GrapheneOS/grapheneos.org#456]
Long time LineageOS user, finally made the transition to GrapheneOS. 
Great job !!! Loving it :+1: 

- SMS (Issue)
In default Android SMS App that comes bundled with Lineage, there is a way to get your Carriage Return (Enter) key back, by going into settings and turning off the hard emoji Icon from the keboard. It doesn't seem to exist in GrapheneOS version. I'm so used to being able to hit Carriage Return to separate lines. I would love if you can add back that feature.

- SMS (Requests)
1. Please could you allow it to use System Theme (I'm using dark)
2. Please could you add a search bar on top? This is so basic, yet critical. Otherwise I have to keep using QK SMS (but its one year old) and Simple SMS has many bugs. 

Thank you again for a great project. Lots of warm wishes to you.

**Comment by ghost** [comment]
1. This is the issue tracker for the website. Not the OS. Please make issues in https://github.com/GrapheneOS/os-issue-tracker/issues
2. We're not going to accept a bunch of requests in one issue. 
3. We do not want to make too many changes to the legacy Messaging app or AOSP Keyboard.

**Comment by ToddCrimson** [comment]
Just did what you asked and added my comments
