### ISSUE TITLE
Expect-CT will be removed from Chromium

### ISSUE THREAD

**Issue by Seirdy** [GrapheneOS/grapheneos.org#481]
Just a heads-up: Chromium, the only browser (to my knowledge) that implemented support for the Expect-CT header, will be deprecating + removing support for it very soon. See the [Intent to Deprecate and Remove on blink-dev](https://groups.google.com/a/chromium.org/g/blink-dev/c/bGLVLwSKNJY/m/nbg4hWckAwAJ).

In other words, the header will be completely ineffective soon and is probably worth removing.

**Comment by thestinger** [comment]
I removed it from all the servers. It hasn't really been useful for a while but I kept it since it did still have a minor impact.
