### ISSUE TITLE
Cellular connection is randomly not available Pixel 5

### ISSUE THREAD

**Issue by bhulk** [GrapheneOS/grapheneos.org#486]
Sometimes after reboot or just randomly throughout the week, cellular connection completely disappears as on an option and the phone says Sim card not inserted (sim card is in fact inserted). Sometimes it takes 5-6 reboots and now for instance it will not come back on no matter the reboots, going into airplane mode, etc. Resetting the SIM card works sometimes for about 2 minutes then the SIM card magically disappears again.  

Phone: Pixel 5
GrapheneOS: 12(SQ3A.220705.004)

What I expect: Cellular will always work.
What actually happens: Cellular does not always work.

**Comment by thestinger** [comment]
Very likely a hardware issue. Not much we can do.
