### ISSUE TITLE
Add kernel docs

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/grapheneos.org#488]
putting this for personal reference and as a reminder to write docs

coral="BUILD_CONFIG=private/msm-google/build.config.floral build/build.sh"
sunfish="BUILD_CONFIG=private/msm-google/build.config.sunfish build/build.sh"
redbull="BUILD_CONFIG=private/msm-google/build.config.redbull.vintf build/build.sh"
raviole="LTO=full BUILD_KERNEL=1 private/gs-google/build_slider.sh"
bluejay="LTO=full BUILD_KERNEL=1 ./build_bluejay.sh"

**Comment by thestinger** [comment]
This is done.

**Comment by thestinger** [comment]
HTML formatting needs to be improved but not doing that until post-13. Also removed legacy 3rd gen / android-prepare-vendor build docs.
