### ISSUE TITLE
Calculator, sms, contacts, dialer, clock apps should be uninstallable

### ISSUE THREAD

**Issue by Umlaut512** [GrapheneOS/grapheneos.org#505]
They are ancient and do not support dark mode or material you. We should be able to remove them through Apps the same way as we can install or remove google play services .Calculator is not essential to the os. As flr the other apps if they truly are crucial maybe it can be possible to uninstall them after the user has a replacement app installed on their device ?

**Comment by thestinger** [comment]
They can be disabled.
