### ISSUE TITLE
GraphineOS - Informative Very Good News - IMPORTANT - PLEASE REVIEW

### ISSUE THREAD

**Issue by kackle435** [GrapheneOS/grapheneos.org#537]
I found the link for the Google Warranty for Ungoogled Phones from Calyxinstitiute.org  Also See Attachment and link [below..](url)

I wanted to give you the heads up on a few things that you may not know.

**Un-Brick A Phone - $39**
https://oneclickroot.com/brick-repair/

Also, when I was researching through the  CalxOS..org and calyxinstitute.org   several days ago **I discovered that Google will honor your warranty on Ungoogled Google phones.**   

**Google Warranty for Ungoogled Phones** 
https://calyxinstitute.org/help/phones/phone-warranties

**[Google Phone Warranties - Calyx Institute_.pdf]**
https://github.com/GrapheneOS/grapheneos.org/files/9864412/Google.Phone.Warranties.-.Calyx.Institute_.pdf)
p/phones/phone-warranties

**Comment by thestinger** [comment]
We're well aware of how the warranties work. Please do not link to anything from Calyx on our issue tracker.
