### ISSUE TITLE
Secondary user has fingerprint unlock disabled. Still allows fingerprint unlocking

### ISSUE THREAD

**Issue by logcatdog** [GrapheneOS/grapheneos.org#548]
steps to reproduce. 

create second user. 

create pin, enable pin.

create fingerprint unlock.

disable fingerprint unlock. 

click power button, unlock with fingerprint still available

reboot solved issue for whatever reason.

**Comment by thestinger** [comment]
There's an issue filed about this upstream AOSP bug already. IIRC it was introduced in Android 13 but I might be misremembering.
