### ISSUE TITLE
Show digital clock in the middle of the screen

### ISSUE THREAD

**Issue by popogomo** [GrapheneOS/grapheneos.org#551]
Hi All,

Thanks for developing such a great OS!

Not a major issue, but it would be great if we will have an option to place digital clock in the middle of the screen, above the fingerprint sensor (in Lock Screen and Always on Display). It is currently displayed in the top left corner of the screen which is not visually pleasant. 
 
Thanks!

**Comment by thestinger** [comment]
We don't plan on adding UI features like this.
