### ISSUE TITLE
Web install fails for Linux users using Gnome when Flashing release

### ISSUE THREAD

**Issue by mariaa144** [GrapheneOS/grapheneos.org#560]
[There are several reports](https://matrix.to/#/!UVEsOAdphEMYhxzTah:grapheneos.org/$dz4AH4OnRmbChuo_rmuV53ZJnyvGfOKAYNNx5z68tsw?via=grapheneos.org&via=matrix.org&via=tchncs.de) of the error `Error: Failed to execute 'claimInterface' on 'USBDevice': Unable to claim interface.` when trying to flash the release. It seems to affect Linux users with Gnome.

**Comment by thestinger** [comment]
This is a GNOME issue. It's likely a bug in GVFS. It's not something we can change. You can replicate it with another WebUSB application.

**Comment by mariaa144** [comment]
Can you give me an example of another WebUSB application which I can demonstrate the issue to upstream?

**Comment by thestinger** [comment]
Google has their own web flasher. If you want another example you'll need to find one.

**Comment by x86pup** [comment]
https://kdrag0n.github.io/fastboot.js/demo/

**Comment by mariaa144** [comment]
It was suggested to temporarily disable automounting with `gsettings set org.gnome.desktop.media-handling automount false` as a workaround. The workaround didn't work for me but perhaps it will give someone an idea.

https://gitlab.gnome.org/GNOME/gvfs/-/issues/658#note_1608140

**Comment by thestinger** [comment]
@mariaa144 I don't have an account there, but you should tell them that the device is not an MTP device when in fastboot mode and fastbootd mode. Other MTP implementations such as the one on Windows aren't breaking it this way. I think their detection rules are overly broad and could be narrower. I'm pretty sure the ids for fastboot mode, fastbootd mode and an MTP device are different.

**Comment by thestinger** [comment]
Alternatively, just link them to my comment here. I don't really feel like making an account there right now.

**Comment by Mikenux** [comment]
Hello!

When a device in fastboot mode is connected to GNOME, it is not mounted as an MTP device. I was able to connect a device and flash with the fastboot.js app linked here. However, this device is old, apparently locked by the vendor because I have a "Security Denied" displayed on the phone (so the flash fails). Anyway, the USB connection in fastboot mode works. I tested on Fedora Workstation 37 (GNOME 43). So maybe it's something other than GNOME.

**Comment by Mikenux** [comment]
I don't have a device to test properly. However, it is necessary to have all the steps to reproduce: which are the successful steps, which are the failed steps, from the "Prerequisites" step to the end.

The GNOME discussion is here: https://discourse.gnome.org/t/need-help-finding-cause-for-graphineos-installation-errors/12720/4

**Comment by thestinger** [comment]
Different phones have different USB ids. It's likely that the issue is the Pixel fastboot and fastbootd mode USB ids were misclassified as MTP devices by whatever is being used by GNOME. We are quite sure this is caused by GNOME because users can install a different desktop environment, reboot into it and avoid the problem.

**Comment by thestinger** [comment]
Also, just to clarify something: the device does not provide MTP in fastboot or fastbootd modes. It only provides fastboot in those modes. Something related to GNOME is connecting and blocking the connection. Also, this is not specific to the web installation. It isn't specifically about WebUSB. It also causes problems with the CLI install with the fastboot tool. It doesn't happen as much for CLI install, presumably because the fastboot CLI tool is faster at reconnecting to the device than fastboot.js can be via WebUSB. It's about whether it wins or loses the race with whatever GNOME is doing to connect.

**Comment by Mikenux** [comment]
OK. Does this happen with a specific Pixel model or with all?

**Comment by thestinger** [comment]
Seems to happen with all.

**Comment by dmp1ce** [comment]
> Also, just to clarify something: the device does not provide MTP in fastboot or fastbootd modes. It only provides fastboot in those modes. Something related to GNOME is connecting and blocking the connection. Also, this is not specific to the web installation. It isn't specifically about WebUSB. It also causes problems with the CLI install with the fastboot tool. It doesn't happen as much for CLI install, presumably because the fastboot CLI tool is faster at reconnecting to the device than fastboot.js can be via WebUSB. It's about whether it wins or loses the race with whatever GNOME is doing to connect.

Interesting. The CLI process worked perfect for me several times. Can this be reproduced by slowing down the CLI script? It might be easier to fix the issue if it can reproduced by a bash script.

**Comment by mariaa144** [comment]
> Also, just to clarify something: the device does not provide MTP in fastboot or fastbootd modes. It only provides fastboot in those modes. Something related to GNOME is connecting and blocking the connection. Also, this is not specific to the web installation. It isn't specifically about WebUSB. It also causes problems with the CLI install with the fastboot tool. It doesn't happen as much for CLI install, presumably because the fastboot CLI tool is faster at reconnecting to the device than fastboot.js can be via WebUSB. It's about whether it wins or loses the race with whatever GNOME is doing to connect.

Interesting. The CLI install worked perfect for me several times. Can this be reproduced using by slowing down the CLI script? It might be easier to fix if the issue can be reproduced consistently.

**Comment by thestinger** [comment]
The script runs the fastboot command for the main flashing process which is a single command doing the whole OS flashing process. It does use multiple fastboot commands but the initial commands happen after sleeping for a short period of time where the problematic code used by GNOME has probably tried to connect to MTP, failed and closed the device. It should be easy to reproduce consistently with the web installer already. Some users did report issues with CLI install but it was much less consistent.

**Comment by Mikenux** [comment]
I don't have a Pixel device. However, maybe knowing exactly at what step this connection problem occurs could help:

> It will automatically handle flashing the firmware, rebooting into the bootloader interface, flashing the core OS, rebooting into the userspace fastboot mode, flashing the rest of the OS and finally rebooting back into the bootloader interface.

**Comment by Mikenux** [comment]
Also, it might be good to have a web app that runs the relevant commands without flashing anything (i.e. without taking the risk of bricking the device) to see if this is reproducible with Pixel phones and any other smartphone.

**Comment by x86pup** [comment]
There's https://kdrag0n.github.io/fastboot.js/demo/ if you want to run your own commands, and the "Unlock bootloader" button simply sends the standard fastboot bootloader unlock command and nothing else.

**Comment by Mikenux** [comment]
Can we refer to the script (command line install) for the sequence of commands?

Also, not knowing how it acts, there is "rebooting into the userspace fastboot mode". I want to know more about this: if it is possible to reboot in this mode while also being able to reboot in non-userspace mode. Also if possible find out how to have this mode for other unlocked phones.

**Comment by ekasprzak** [comment]
Hi, freshly bought Pixel 6a and wanted to flash GOS, on Ubuntu 22.04 I have "claimInterface" issue (every time), but I don't think it's actually GNOME/GVFS related.

I completely stopped and disabled all gvfs* services - didn't change a thing.

Fortunately, I have another laptop with Fedora 35, which uses vanilla GNOME.
I didn't touch anything - no tweaking automount via gsettings, no stopping gvfs services, so all the gnome/gvfs processes were working and WebInstall succeeded without any issues.

So, this seems like more Ubuntu-related issue, not GNOME itself.

The official instructions (https://grapheneos.org/install/web#connecting-phone) and the reason for closing this issue ("This is a GNOME issue" which is probably wrong) might point users in wrong direction - looking for how to stop gvfs etc, which will not help at all.

**Comment by mariaa144** [comment]
Strange. I experienced this issue on Arch Linux. It may still be related with Gnome but might be a race condition which only occurs sometimes.

**Comment by prez** [comment]
Hi, just wanted to say KDE has the same bug/behaviour. Maybe the documentation should be updated to reflect this.

**Comment by SzilvasiPeter** [comment]
For me, executing the following command solved the issue:
```
sudo systemctl stop fwupd.service
```

**Comment by thestinger** [comment]
Stopping fwupd has recently been added to the documentation. It's buggy and incorrectly connects to fastboot devices but they appear unwilling to acknowledge or fix it.

**Comment by Mikenux** [comment]
@thestinger: Is there an open issue for this?

**Comment by thestinger** [comment]
I filed an issue but asked for it to be deleted afterwards. fwupd fixed the issue in their development branch. I don't think they've done a new release yet and don't know when they will. It will take years for it to reach Linux distributions.
