### ISSUE TITLE
add hint in WebInstaller page next to the button that this is the button (and only works in mentioned browsers)

### ISSUE THREAD

**Issue by derFliegendeHamburger** [GrapheneOS/grapheneos.org#580]
this in meant as an enhancement to increase ease of use and prevent a pitfall.
For working with computers I use other browsers than those recommended (clearly and explicitly) on the WebInstaller page.
In consequence I did read and execute the prerequisites while still using firefox. When arriving at the gray rounded box "unlock bootloader" I had no clue how/where to get the "unlock program" to execute this.  It took me some source code reading and searching to figure  out this was embedded calling  functionality from within the web page display and to work from within recommended browser

Suggestion: add hint next to the first button stating this gray box will become active when using a recommended browser.
Thanks

**Comment by thestinger** [comment]
We already cover this and can't just keep adding more text. It makes it harder not easier.
