### ISSUE TITLE
Volume Bug

### ISSUE THREAD

**Issue by ghost** [GrapheneOS/grapheneos.org#584]
Hi,
I use Pixel 6a with latest GrapheneOS.
I have set my Call Volume at 75%.
Now, whenever I call someone or I got call from someone, the volume level goes to 100% automatically on call engage.
Its very annoying. Everytime I have to adjust down while conversation.
Please help
Thanks

**Comment by thestinger** [comment]
Are you sure you're not setting a different volume? Are you using the standard Dialer app? This is not reproducible and is likely a misunderstanding.

**Comment by ghost** [comment]
I'm sure of proper setting. And I use only graphemes built-in dialer.

**Comment by ghost** [comment]
Can I send you video showing that?
