### ISSUE TITLE
Law enforcement inquiries policy

### ISSUE THREAD

**Issue by dscotese** [GrapheneOS/grapheneos.org#597]
I would like assurances that if law enforcement inquiries are made to the devs or the owners of grapheneos.org or to anyone whose response can be expected to affect many Graphene OS users, the inquiry and the publicly permissible part(s) of the response will be published, for example in the Telegram group or the Matrix server (since either will show up in the other).

If this policy is not in place, I ask that it be instituted.  If it already is, where can we review it?

Thanks!

**Comment by thestinger** [comment]
No law enforcement requests have been made to GrapheneOS and if there were any we would publish it. We have a legal fund and a great lawyer already available to defend the project from further attacks. The project has already been attacked through legal and other methods by companies, criminals and others. We would publish information on this in a more prominent place than the chat rooms. Not really sure what you want.

**Comment by dscotese** [comment]
I love it!  Assurances would be available if it were part of the FAQ.  AgoraDesk.com has a link at the bottom of their website called "Law Enforcement Inquiries" which leads directly to their policy.  It would be nice if this were the case (or even if just "law enforcement" was addressed somewhere in the FAQ).

I apologize for not making it clearer when I first opened this issue.  I agree that the chat rooms are not prominent enough, but it seems that this issue on Github is currently the only place where it is published, and this is even less prominent than the chat rooms, I think!  Your answer, by itself, would make a great addition to the "About" section on the front page, but I think a general description of where it would be published is a good idea.  It would also be nice if the website had a warrant canary that would have to be altered if any inquiries do come in.

**Comment by An-anonymous-coder** [comment]
> It would also be nice if the website had a warrant canary that would have to be altered if any inquiries do come in.

I second this. Gag orders and legal restrictions happen, and the only way around it would be a warrant canary. I can open a pull request for this if you'd like, @thestinger.

**Comment by thestinger** [comment]
A coarse warrant canary is not an appropriate way of dealing with it. It won't be accepted. It's a misguided idea and provides an easy way to harm the reputation project via a legal attack despite us not providing anything. Why would we do that?

**Comment by dscotese** [comment]
Please propose any warrant canary you feel would address the issue, however specific it might be. My search for how GrapheneOS would handle a law enforcement inquiry led me here and has produced your great question, "Why would we do that?" However, it does not appear that any progress has been made to help anyone who has the same curiosity as mine (and perhaps that of @An-anonymous-coder) except for the existence of this (now closed) issue.  I don't think that fits the bill.

@thestinger has provided the first element of what I wanted ("assurances") in the same reply that said "Not really sure what you want." No worries, you already gave it to me.

My proposal for a warrant canary arises from the necessity to clarify this claim: "No law enforcement requests have been made to GrapheneOS and if there were any we would publish it." I assume it was true at the time it was written, but there was no timeframe attached to the claim in which such a request would be published. I agree that a warrant canary that is too coarse would create more problems than it solves. However, simply adding a timeframe to the policy might make it specific enough to solve more problems than it creates. When I have used warrant canaries, they started with "As of (date and time), [statement of important fact]. This canary will be updated within [timeframe] of any request to update it unless [important fact is no longer true]." That can get bothersome if too many requests come in, but there are other ways to provide a timeframe, such as "The 'as-of' date should not be more than [some age]," in which case it need only be updated periodically.

**Comment by thestinger** [comment]
No, it creates a weakness in the project for no reason.
