### ISSUE TITLE
Calling issues

### ISSUE THREAD

**Issue by Shadow-Hunt3r** [GrapheneOS/grapheneos.org#649]
Hi, I have had my phone, Pixel 6a, running GrapheneOS for a while and for some reason i currently am unable to make or receive any calls using the SIM card, it does for some reason allow me to use mobile data however.
I checked the following to see why I was unable to make and receive phone calls:
APN being accurately filled out, Resetting SIM card, testing the SIM in another device incase it was damaged, and following other instructions listed in the FAQ regarding these issues

What is supposed to happen when making or receiving a call:
Phone rings or displays dialing when cellular data is available and phone is active

What occurs when doing so:
Attempts to make a call instantly get ended before it even starts to dial and anyone attempting to call me get sent straight to voicemail

I can provide screen recordings of this occuring issue and screenshots requested with sensitive data such as personal numbers being blurred out

**Comment by r3g-5z** [comment]
Please ask for support in our Matrix room. This is the website issue tracker.

https://grapheneos.org/contact#community
