### ISSUE TITLE
CLI install instructions - Arch android-tools version issue

### ISSUE THREAD

**Issue by jbiel** [GrapheneOS/grapheneos.org#652]
I ran through a CLI install (using a fully up to date Arch box) today on my Pixel 7 Pro (it had the April 2023 update) and was unable to complete it after three tries.  I used the latest version of `android-tools` from the Arch repo (`33.0.3-3`), but that was insufficient. Once I built/installed a new package of `android-tools` using version `34.0.0` it worked right away.

The [CLI install docs](https://grapheneos.org/install/cli) specifically call out that that the minimum Arch package version of `android-tools` for Pixel 7 devices is `33.0.3-3`, but this doesn't seem to be the case. This is a somewhat awkward situation since the package has been flagged for ~1.5 month. I was going to submit a PR against this repo to reword the page, but I'm not sure how the project would like to handle communicating this. Hopefully the maintainer of Arch's `android-tools` package will update it soon and this concern will mostly go away.

If you're curious about what error occurred, I've put a snippet below. All three failures were identical. During these attempts the phone was displaying the flash/erase screen instead of the bootloader screen. The image that I flashed was `cheetah-factory-2023041100.zip`.

```
Writing 'vendor_kernel_boot_b'                     OKAY [  0.076s]
extracting super_empty.img (0 MB) to disk... took 0.000s
Rebooting into fastboot                            OKAY [  0.000s]
< waiting for any device >
Sending 'super' (5 KB)                             OKAY [  0.002s]
Updating super partition                           FAILED (Status read failed (No such device))
fastboot: error: Command failed
< waiting for any device >
Rebooting into bootloader                          FAILED (Write to device failed (Cannot send after transport endpoint shutdown))
fastboot: error: Command failed
```

**Comment by thestinger** [comment]
I do think 33.0.3 is the minimum requirement but it's likely 34.0.0 handles some USB problems better.

**Comment by jbiel** [comment]
OK, 33.0.3 absolutely did not work for me and 34.0.0 worked the first time. I used the stock USB-C cable (which I don't use much.) I created this issue in hopes of saving other people time in case they encounter the same issue.
