### ISSUE TITLE
Google Play Apps not automatically updating non Owner Profile

### ISSUE THREAD

**Issue by User1966** [GrapheneOS/grapheneos.org#658]
GIVEN I have enabled 'silent' System Updates in Owner Profile
AND I have installed a new profile with Google Play and Google Play Services (Sandboxed)
WHEN see 'Apps are up-to-date' as a silent notification
AND I check the Google Play Store updates
THEN I see that App updates can be installed/and are not up to date

Expected:
The app update and google play need to sync
As in you can just have the google play store automatically update
Is the notification just for the GrapheneOS apps?
Is there a way to automatically update the apps via Google Apps Sandboxed?

Provide secure delivery method for attachments
If this is completely not possible, perhaps add a wiki on how to automatically ensure the 'google play' apps are kept up to date automatically.

**Comment by thestinger** [comment]
The notification is from the GrapheneOS app repository client and is only for that.
