### ISSUE TITLE
web installer: Brave now interferes with WebUSB, maybe an additional hint is required.

### ISSUE THREAD

**Issue by Peacock365** [GrapheneOS/grapheneos.org#672]
@thestinger

Hello GrapheneOS team,

recently the Brave Browser implemented randomizing USB serial numbers per device:

https://github.com/brave/brave-browser/issues/30041

This has already led to reports of some workflows not working:

https://reddit.com/r/brave_browser/comments/13m80f4/webusb_not_working/

The installation of GrapheneOS should happen through a Chromium-based browser. Brave is such a Chromium-based browser, however its interference with WebUSB is unique to it. To ensure a smooth installation procedure, please consider adding a hint or note that Brave users should turn their "Fingerprinting blocking" to "Disabled" as a per-site exception (using the Brave button in the address bar) before beginning the installation procedure. I would also suggest adding a note that this has to happen due to their meddling with WebUSB, and not because grapheneos.org wants to fingerprint users visiting the website.

Thank you for your attention.

**Comment by matchboxbananasynergy** [comment]
Has someone confirmed that Brave with this feature built-in makes the web installer not work, or re we making an assumption that needs to be put to the test at this point?

**Comment by irelativism** [comment]
@matchboxbananasynergy  yeah I can confirm it didn't work even after following steps regarding brave settings for USB. I was unable to install my pixel4 successfully only after installing chromium I was successful.

**Comment by dev-goalz** [comment]
I can confirm that without any security changes Brave works fine on Ubuntu 24 with WebUSB. Flashing, unlocking etc.

**Comment by thestinger** [comment]
@jmvermeulen Did you have to disable Brave Shields for grapheneos.org?

**Comment by dev-goalz** [comment]
> @jmvermeulen Did you have to disable Brave Shields for grapheneos.org?

No, Shields are up. Just did a USB permissions reset and it still works after reconfirming the device selection.
Running [Version 1.68.128 Chromium: 127.0.6533.73 (Official Build) (64-bit)]

**Comment by thestinger** [comment]
@j
