### ISSUE TITLE
Drawer Problem

### ISSUE THREAD

**Issue by ghost** [GrapheneOS/grapheneos.org#740]
Hi,
Thanks for such a secure OS.
I run the OS on Pixel 6A
Problem: When I drop down upper drawer, I see "Internet"  field / Button in Green color as if it is active.
For example, there is "Hot Spot" field / Button which remains Gray if it is not active. And it turns in to Green Color when it is activated and becomes Gray when it is not Activated.
But the Internet button or field remains Always Green  whether it is activated or not. 
So I have to tap it every time to see whether it is activated or not. Such a waste of time.

Is it kept this way by Default or is it a bug.

Thanks a lot

**Comment by thestinger** [comment]
That's simply how it works. It's not changed by GrapheneOS.

**Comment by thestinger** [comment]
You can see which networks are connected in the status bar.
