### ISSUE TITLE
Pixel 8 Pro "husky" support

### ISSUE THREAD

**Issue by prononext** [GrapheneOS/grapheneos.org#764]
Dear wonderful GrapheneOS Team, 

what are the plans for Pixel 8 Pro, when do you think a GrapheneOS Version for the "husky" is ready to use?

Thank you very much for the development effort. Your Ideas and the OS is just wonderful and I am using it for years already. 

Hoping to hear back soon. 
Best Regards

**Comment by thestinger** [comment]
We don't provide timelines for device support. We're still working on Android 14 stabilization.
