### ISSUE TITLE
confirmation-email in forum not working

### ISSUE THREAD

**Issue by Ghuser197** [GrapheneOS/grapheneos.org#773]
Hi,
dont know if this fits here..

i created an account on https://discuss.grapheneos.org/ 2 days ago, but i never got a confirmation email(resent it x-times).
I also tried to change e-Mail adress, it took the change once and it showed to send it to th New adress but after relogin the old adress is still there.

Anyway i never got a confirmation  mail on no E-Mail adress 
Hopfuly some1 can help me with this...thx

**Comment by thestinger** [comment]
Please give account name.

**Comment by Ghuser197** [comment]
Forumuser179

Thx

**Comment by thestinger** [comment]
Please send an email to contact@grapheneos.org from the email you want to use with your user name in the email subject.

**Comment by thestinger** [comment]
Let me know after you do that.

**Comment by Ghuser197** [comment]
Done

**Comment by thestinger** [comment]
@Ghuser197 It's activated now. We sent a reply in response to your email. Can you check if you received that? It's possible your email provider is blocking emails from mail.grapheneos.org. Our discussion forum was attacked by a Russian group automatically creating accounts using other people's emails to send them confirmation emails from many forums as spam emails. They targeted many politicians in Europe, official NATO emails, etc. We blocked it from continuing to happen but a consequence is that our email server's reputation was severely harmed especially for the discussion forum and especially for account confirmation emails. If you can receive regular emails from us like the one we just sent in reply, that would be good to know. If you can't, we need to contact your provider about it.
