### ISSUE TITLE
Device support update

### ISSUE THREAD

**Issue by errordriven** [GrapheneOS/grapheneos.org#788]
The section **Device Support** 
[Which devices are supported? ](https://grapheneos.org/faq#supported-devices)
still lists 
- Pixel 5 (redfin)
- Pixel 4a (5G) (bramble)

which reached EOL recently.

**Comment by thestinger** [comment]
They're not end-of-life yet. You're confusing minimum support time with end-of-life time. They received the November 2023 update.
