### ISSUE TITLE
Consider adding Android app developer compatibility and best practice guide

### ISSUE THREAD

**Issue by steven-ahfu** [GrapheneOS/grapheneos.org#873]
Forgive me if this is available somewhere and I've missed it.

Consider adding a prominent "android app development compatibility & best practices" section to the website. 

Independent android developers may unintentionally limit GrapheneOS compatibility in various ways (such as when switching over to [Play Integrity API](https://grapheneos.org/articles/attestation-compatibility-guide)). It would be great to provide a development guide with clear instructions for ensuring compatibility, and solutions for remediating existing incompatibilities.

Additionally, this may be a great place to offer opinionated best practices for android development in general.
* How and where developers can publish apps (e.g. F-Droid, GitHub, Google Play Store)
* Best practices for respecting user privacy & security (e.g. "App monetization options, offer license key for paid version on [ProxyStore](https://digitalgoods.proxysto.re/en)")
* Ways to implement common app behaviors without requesting unnecessary permissions
* etc

**Comment by thestinger** [comment]
We already cover attestation and there isn't really anything else specific to GrapheneOS. We're not going to be making generic guides for app developers.
