### ISSUE TITLE
Link to an article abour GSMA TS.43 leads to a page not found 

### ISSUE THREAD

**Issue by AtmosphericIgnition** [GrapheneOS/grapheneos.org#938]
At the bottom of [grapheneos.org/usage](grapheneos.org/usage), there is a link to [gsma.com](gsma.com) leading to some reading about the GSMA TS.43 standard. This link currently leads to a "page not found" error on the GSMA site.
After a quick search, it seems the original document was taken down, because it is about an older version of the standard. I found a document about a new version of the standard.

According to the Wayback Machine, the [revised pdf](https://www.gsma.com/newsroom/wp-content/uploads//TS.43-v11.0-Service-Entitlement-Configuration.pdf) I found is similar to the [old one](https://web.archive.org/web/20230517234828/https://www.gsma.com/newsroom/wp-content/uploads//TS.43-v9.0.pdf) which was removed from the site.

**Comment by thestinger** [comment]
Linked is now updated.

**Comment by thestinger** [comment]
It's questionable if we really need to link to this here but I'll leave it for now.
