### ISSUE TITLE
file system type raw not supported

### ISSUE THREAD

**Issue by pjvleeuwen** [GrapheneOS/grapheneos.org#97]
When running `./flash-all.bat` from https://releases.grapheneos.org/crosshatch-factory-2020.04.14.23.zip
on Windows 10 PS with connected Pixel 3 XL I get:

```
...
Erasing 'userdata'                                 OKAY [  8.092s]
Erase successful, but not automatically formatting.
File system type raw not supported.
Erasing 'metadata'                                 OKAY [  0.009s]
Erase successful, but not automatically formatting.
File system type raw not supported.
Finished. Total time: 95.348s
```

Based on current documentation https://grapheneos.org/install it is unclear whether this `not automatically formatting` is expected behavior.

Please clarify for ease of mind of users.

**Comment by thestinger** [comment]
This is normal. It lets the OS format it.
