### ISSUE TITLE
flash-all.bat does not end in reboot to new operating system

### ISSUE THREAD

**Issue by pjvleeuwen** [GrapheneOS/grapheneos.org#98]
When running `./flash-all.bat` from https://releases.grapheneos.org/crosshatch-factory-2020.04.14.23.zip
on Windows 10 PS with connected Pixel 3 XL...

The documentation https://grapheneos.org/install
says:

> Wait for the flashing process to complete and for the device to boot up using the new operating system.

At the end of the running `./flash-all.bat` the phone stays on the fastbootd screen. I can reboot from there. It is just that the current documentation suggests a different expected state.

Note : issue #97 which might be the cause of the different end-state.

Please correct / clarify documentation such users can be more confident they are still on the right track.

**Comment by thestinger** [comment]
Thanks, fixed this. I don't want all the changes in your pull request as is so I'll probably just address this issues based on your reports.
